language: node_js
node_js:
  - 18
  - 17
  - 16
  - 15
  - 14
  - 13
deploy:
  provider: npm
  email: boran@boranseckin.com
  on:
    tags: true
    repo: boranseckin/2fa-utils
  api_key:
    secure: MgloyVj1/mVn7gHj7Su/ieIFhvBR7uRNo0vdfxcK74YTKSbk8vNhq4aXWpey0WWAsc2FrhKt00ieLAEolTS6hEbykY5DslS5WAmQncKPkUqBridvo4yrYPrgbe0pJITyiXMAgNqbppt+kKDK6Lr3N7CoTVVvf3tv+XeeSAqW0itq2XwH9S8ITTFUfREcK+/Ph6tGh85y5rTYKaaf5VKrvYdE/f+ExLbd5v/1wcUuZAu8dwaxqsaIGpDVdeRyxoPJY91zIw+/Zrr8kqid7VRmUUoDBXup5P04Q5C8iN/dxoY7kqghByyzuXVjAwBTvWStwA84LlsUOOlBiZTNPT8Y4gLjF1Hq0qSQmaYjV2K1g0ZRVy4zIm6fWA65wPDBnLt3qLLmUa2rl40zIh8xzHwueuIJCrUhBaZMXM6f2rWmxeMCnjxVzNABvfCvk/aEsR4J0iwo0+4PcBTBC/DIIi7fp9s5BwoRmlT/8/rHjSlDppKGxsqQAxG0nDp0BIjIpGYymzguLshmaEIr9Qhuqw00dnqs/0uO1h228yjLmF1943pVw4ver4A2uXdxcUEbeTnCCmlXvg1K6wPlpMFXSAzBlNnrLgaOZBHIvbHhAqjYrjRZhROkMBYn8JRrOGOcQG30qRQX45LskRrbshfyne5Xd/1mPegVafkhN9dlOiLKiLA=
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: never
